FROM ghcr.io/mlflow/mlflow:v2.9.2

RUN pip install --no-cache-dir psycopg2-binary

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "postgresql://forecast_user:forecast_password@postgres:5432/forecast_db", "--default-artifact-root", "/mlflow/artifacts"]