FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Используем зеркало для ускорения
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.org/simple/ --trusted-host pypi.org

COPY src/streamlit/ ./streamlit/

EXPOSE 8501

CMD ["streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]